PREFIX dwellings:  <http://vbartonicek.cz/swe/dwellings/#>
PREFIX dbo:  <http://dbpedia.org/ontology/#>
PREFIX municipalities:  <http://vbartonicek.cz/swe/municipalities/#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

select * where {
   ?dwellings a dwellings:value ;
     municipalities:obec_nazev ?municipality .
   VALUES (?municipality) { ("Středokluky"^^<http://www.w3.org/2001/XMLSchema#string>) }
}
