PREFIX ex: <http://vbartonicek.cz/swe/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcam: <http://purl.org/dc/dcam/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?URI a ex:Dwellings;

    qb:value a rdf:Property, qb:MeasureProperty;
    rdfs:label "Dwellings built count"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:integer .

    ex:staproKod ?staproKod;
    ex:tb_cis ?tbCis;
    ex:tb_kod ?tbKod;
    ex:vuzemi_cis ?vuzemiCis;
    ex:vuzemi_kod ?vuzemiKod;
    ex:year ?year;
    ex:dateFrom ?dateFrom;
    ex:dateTo ?dateTo;
    ex:staproTxt ?staproTxt;
    ex:tbTxt ?tbTxt;
    ex:vuzemiTxt ?vuzemiTxt;
}
WHERE {
  BIND (URI(CONCAT('http://vbartonicek.cz/swe/dwellings/', ?idhod)) AS ?URI)
  BIND (xsd:integer(?hodnota) AS ?value)
  BIND (xsd:integer(?stapro_kod) AS ?staproKod)
  BIND (xsd:integer(?tb_cis) AS ?tbCis)
  BIND (xsd:integer(?tb_kod) AS ?tbKod)
  BIND (xsd:integer(?vuzemi_cis) AS ?vuzemiCis)
  BIND(IRI(CONCAT("http://vbartonicek.cz/swe/municipalities/", ?vuzemi_kod)) as ?vuzemiKod)
  BIND (xsd:integer(?rok) AS ?year)
  BIND (xsd:date(?casref_od) AS ?dateFrom)
  BIND (xsd:date(?casref_do) AS ?dateTo)
  BIND (STRLANG(?stapro_txt, "cs") AS ?staproTxt)
  BIND (STRLANG(?tb_txt, "cs") AS ?tbTxt)
  BIND (STRLANG(?vuzemi_txt, "cs") AS ?vuzemiTxt)
  # Filtered records to have non-zero values from year of 2017 in reason of dataset's size
  FILTER(?value != 0)
  FILTER(?year = 2017)
}

OFFSET 1
#LIMIT 10
