PREFIX ex: <http://vbartonicek.cz/swe/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?URI a ex:Population;
    ex:municipality ?municipalityId;
    ex:population ?population;
    ex:populationMen ?populationMen;
    ex:populationWomen ?populationWomen;
    ex:averageAge ?averageAge;
    ex:averageAgeMen ?averageAgeMen;
    ex:averageAgeWomen ?averageAgeWomen .

  ?municipalityId a ex:Municipality;
    ex:municipalityName ?municipalityName .

}
WHERE {
  BIND (URI(CONCAT('http://vbartonicek.cz/swe/population/', ?b)) AS ?URI)
  BIND(IRI(CONCAT("http://vbartonicek.cz/swe/municipalities/", ?b)) as ?municipalityId)
  BIND (STRLANG(?c, "cs") AS ?municipalityName)
  BIND (xsd:integer(?d) AS ?population)
  BIND (xsd:integer(?e) AS ?populationMen)
  BIND (xsd:integer(?f) AS ?populationWomen)
  BIND(xsd:double(REPLACE(STR(?g),"\\,",".")) AS ?averageAge) .
  BIND(xsd:double(REPLACE(STR(?h),"\\,",".")) AS ?averageAgeMen) .
  BIND(xsd:double(REPLACE(STR(?i),"\\,",".")) AS ?averageAgeWomen) .
}

OFFSET 5
#LIMIT 10
