PREFIX ex: <http://vbartonicek.cz/swe/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcam: <http://purl.org/dc/dcam/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?URI a ex:Population;
    ex:municipality ?municipalityId;

    qb:population a rdf:Property, qb:MeasureProperty;
    rdfs:label "population"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:integer .

    qb:populationMen a rdf:Property, qb:MeasureProperty;
    rdfs:label "Men population"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:integer .

    qb:populationWomen a rdf:Property, qb:MeasureProperty;
    rdfs:label "Women population"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:integer .

    qb:averageAge a rdf:Property, qb:MeasureProperty;
    rdfs:label "average age"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:decimal .

    qb:averageAgeMen a rdf:Property, qb:MeasureProperty;
    rdfs:label "average men age"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:decimal .

    qb:averageAgeWomen a rdf:Property, qb:MeasureProperty;
    rdfs:label "average women age"@en;
    rdfs:subPropertyOf sdmx-measure:obsValue;
    rdfs:range xsd:decimal .

  ?municipalityId a ex:Municipality;
    ex:municipalityName ?municipalityName .

}
WHERE {
  BIND (URI(CONCAT('http://vbartonicek.cz/swe/population/', ?b)) AS ?URI)
  BIND(IRI(CONCAT("http://vbartonicek.cz/swe/municipalities/", ?b)) as ?municipalityId)
  BIND (STRLANG(?c, "cs") AS ?municipalityName)
  BIND (xsd:integer(?d) AS ?population)
  BIND (xsd:integer(?e) AS ?populationMen)
  BIND (xsd:integer(?f) AS ?populationWomen)
  BIND(xsd:float(REPLACE(STR(?g),"\\,",".")) AS ?averageAge) .
  BIND(xsd:float(REPLACE(STR(?h),"\\,",".")) AS ?averageAgeMen) .
  BIND(xsd:float(REPLACE(STR(?i),"\\,",".")) AS ?averageAgeWomen) .
}

# Skipping the table header
OFFSET 5
#LIMIT 10
